### ISSUE TITLE
version sailfish 3.1.0.11

### ISSUE THREAD

**Issue by geminis65** [wdehoog/sailfish-bacon-images#11] opened 2019-08-26 16:10 UTC
good afternoon, one question: you are not going to upload the sailfish 3.1.0.11.release image a greeting

**Comment by wdehoog** [comment] 2019-08-26 16:54
I am sorry but I do not have one. I tried to build it but the UI stutters and crashes. I am afraid the problem is too complex for me. Maybe I'll give it another try in the future.

**Comment by htot** [comment] 2019-08-26 18:47
Help wanted / Won't fix?

**Comment by xsetiadi** [comment] 2019-08-27 07:15
please build next version if you have time sir

Regards, from Indonesia

**Comment by wdehoog** [comment] 2019-12-08 09:25
I just released 3.2.0.12

**Closed as completed by wdehoog** 2019-12-08 09:25 UTC
